### PR TITLE
BCMOHAD-16477||Flow fix for date sort for hospital

### PR DESCRIPTION
**Pull request by ahshaik1**

### CODE REVIEW

**Review by mhussaincgi — APPROVED** [review]
Formula update for Hospitalization record will not effect any other stuff.

**Review by rahul-mantri — APPROVED** [review]
Approved @ahshaik1 

CC: @NataliaNikishina, @anudishCGI, @mhussaincgi

**Review by NataliaNikishina — APPROVED** [review]
@ahshaik1 approved
cc: @anudishCGI

**Review by anudishCGI — APPROVED** [review]
Approved @NataliaNikishina @ahshaik1

**Pull request merged**
