### PR TITLE
Update to document generation

### PR DESCRIPTION
**Pull request by anudishCGI**
Hello @crystalz2022 and @NataliaNikishina 
Creating a PR for publishing the cosmetic changes of Document Generation. Could you please review it.
Thank You

### CODE REVIEW

**Comment by anudishCGI** [comment]
Adding @rahulmantriSFDC for review.
Thank you

**Review by rahul-mantri — APPROVED** [review]
Approved @anudishCGI 

CC: @crystalz2022 @NataliaNikishina

**Review by NataliaNikishina — APPROVED** [review]
@anudishCGI approved
cc: @crystalz2022 @rahulmantriSFDC

**Review by NataliaNikishina — APPROVED** [review]
@anudishCGI Approved.
cc: @crystalz2022 @rahulmantriSFDC

**Review by crystalz2022 — APPROVED** [review]
Approved @anudishCGI

**Review by rahul-mantri — APPROVED** [review]
Approved @anudishCGI 

Please merge @NataliaNikishina and I'll deploy the Datapacks.

Thank you

**Pull request merged**
