### PR TITLE
updating height and width of datatable to auto in Pharmacare Account

### PR DESCRIPTION
**Pull request by anudishCGI**
Updated styling of lightning data table of  Pharmacare Account to auto

### CODE REVIEW

**Comment by anudishCGI** [comment]
@crystalz2022  @NataliaNikishina  @rahulmantriSFDC 
Could you please verify it.
This request is based on the observation seen yesterday in the UAT environment smoke testing. Thank You!

**Review by rahul-mantri — APPROVED** [review]
Validation is successful.
Looks good to me.

**Review by crystalz2022 — COMMENTED** [review]
Let's wait until we get the feedback from the business

**Comment by anudishCGI** [comment]
No longer valid

**Pull request closed without merging**
