### PR TITLE
Updating CC and FC on account grid

### PR DESCRIPTION
**Pull request by anudishCGI**

### CODE REVIEW

**Review by rahul-mantri — APPROVED** [review]
Validation is successful. Looks to good to me.

**Comment by anudishCGI** [comment]
Added destructive changes as well in the PR.
Removed unused apex classes. This should be the final PR for the release.
Please review @crystalz2022  @rahulmantriSFDC 
Thank You

**Review by rahul-mantri — APPROVED** [review]
Changes Approved

**Comment by anudishCGI** [comment]
Adding @cgijeffolsen for reviewing the PR as per direction.
Thank You!

**Review by cgijeffolsen — APPROVED** [review]
Thank you Anudish for this important cleanup activity. Approved.

**Pull request merged**
