### PR TITLE
customMetadata added for Keycloak Sol.

### PR DESCRIPTION
**Pull request by crystalz2022**
customMetadata added for Keycloak Sol.

### CODE REVIEW

**Review by cgijeffolsen — APPROVED** [review]
This matches requirements for the latest approach on KeyCloak. Thank you.

**Comment by rahulmantriSFDC** [comment]
Validation failed. 

Please check. @crystalz2022

**Review by anudishCGI — APPROVED** [review]
Approved @crystalz2022 
CC: @NataliaNikishina

**Comment by crystalz2022** [comment]
Added one more commit to correct the issue "TPL_Standard_User  The user license doesn't allow the permission: View All Product2"

**Review by rahul-mantri — APPROVED** [review]
Approved @crystalz2022 

Please review @NataliaNikishina @anudishCGI

**Review by anudishCGI — APPROVED** [review]
Approved @crystalz2022 
CC: @NataliaNikishina  @rahulmantriSFDC

**Review by NataliaNikishina — APPROVED** [review]
@crystalz2022 approved

**Pull request merged**
