### PR TITLE
Adding Criteria source system ID check

### PR DESCRIPTION
**Pull request by anudishCGI**
Updated Healthcare Cost validation rules by adding source system ID check to skip them from executing for integration records
Could you please review @crystalz2022  @NataliaNikishina  @rahulmantriSFDC 
Thank You

### CODE REVIEW

**Review by NataliaNikishina — APPROVED** [review]
@anudishCGI approved 
cc: @crystalz2022 @rahulmantriSFDC

**Review by rahul-mantri — APPROVED** [review]
Approved @anudishCGI 

cc: @crystalz2022, @NataliaNikishina

**Review by crystalz2022 — APPROVED** [review]
Approved @anudishCGI

**Review by cgijeffolsen — APPROVED** [review]
@anudishCGI Approved

**Pull request merged**
