### PR TITLE
Added the Reason for Closing field in the Path

### PR DESCRIPTION
**Pull request by RanadheerRG**

### CODE REVIEW

**Review by adutta33 — APPROVED** [review]
Looks good to me.

**Comment by rahul-mantri** [comment]
@RanadheerRG Please update your JIRA ticket with the necessary details so that I can review the PR.

**Comment by RanadheerRG** [comment]
Added the Reason For Closing field to the path so that when we try to change the status to close then we can directly update it at the path

**Review by rahul-mantri — APPROVED** [review]
Updated the PR with the requested changes and JIRA ticket is also updated. Now, this looks good to me

**Pull request merged**
