### PR TITLE
BCMOHAD-15763||Mass Update Components

### PR DESCRIPTION
**Pull request by ahshaik1**

### CODE REVIEW

**Review by NataliaNikishina — APPROVED** [review]
@ahshaik1 The branch has been successfully validated so I am approving this PR.
cc: @crystalz2022 @cgijeffolsen @rahulmantriSFDC

**Review by rahul-mantri — APPROVED** [review]
Validation is successful. So approving this.

CC: @NataliaNikishina, @crystalz2022, @cgijeffolsen

**Review by crystalz2022 — APPROVED** [review]
approved @ahshaik1

**Review by cgijeffolsen — APPROVED** [review]
@ahshaik1 Approved

**Pull request merged**
