### PR TITLE
 Updating doc gen for front screen

### PR DESCRIPTION
**Pull request by anudishCGI**
Document Generation Screen update. 
Could you please verify the changes @rahulmantriSFDC @NataliaNikishina @crystalz2022 
Thank You

### CODE REVIEW

**Review by crystalz2022 — APPROVED** [review]
approved @anudishCGI

**Review by rahul-mantri — APPROVED** [review]
Approved @anudishCGI 

CC: @crystalz2022 @NataliaNikishina

**Comment by rahul-mantri** [comment]
@NataliaNikishina Once you approve, I'll deploy the datapacks to QAA.
Thank you

**Review by NataliaNikishina — APPROVED** [review]
@anudishCGI approved

**Pull request merged**
