### PR TITLE
Updating OmniStudio Components for DocGen

### PR DESCRIPTION
**Pull request by anudishCGI**

### CODE REVIEW

**Comment by anudishCGI** [comment]
A PR consisting OmniStudio changes related to Document Generation and respective file updates @NataliaNikishina @crystalz2022 
Thank You

**Comment by NataliaNikishina** [comment]
@herman-ovodov-cgi Please review and approve.

**Review by herman-ovodov-cgi — COMMENTED** [review]
@anudishCGI to clarify, does this PR include all OmniStudio updates made since last commit of OmniStudio to GitHub? If no, please include other OmniStudio components as well.

**Comment by anudishCGI** [comment]
@herman-ovodov-cgi @NataliaNikishina 
Closing the PR due to update in folder structure change of OmniStudio on discussion with @crystalz2022 
Thank You

**Pull request closed without merging**
