### PR TITLE
Code changes on Ambulance and Pharmacare

### PR DESCRIPTION
**Pull request by anudishCGI**
Apex classes:
HCCCostAmbulanceHelper
HCCCostAmbulanceRecord
HCCCostAmbulanceRecordTest
HCCCostController
HCCCostControllerTest
HCCCostPharmacareRecord
HCCCostPharmacareRecordTest

Custom Label Update: Created new label TPL_Records_Created_Today 

LWC Components: 
ambulanceRecordsAccount
ambulanceRecordsCase
customDataTableLookup
datatableLookup
pharmacareRecordsAccount
pharmacareRecordsCase

Static Resources:
CustomDataTable.css

@crystalz2022  @NataliaNikishina Please review the changes. Let me know in case of any issues.

### CODE REVIEW

**Review by NataliaNikishina — APPROVED** [review]
@anudishCGI approved

**Review by rahul-mantri — APPROVED** [review]
Validation is successful.

**Comment by anudishCGI** [comment]
Hello @NataliaNikishina  @crystalz2022 @rahulmantriSFDC 
Could you please check the PR if all good. I just now added one change which we missed adding it earlier to the file. No new file updates. I validated it against QA and it gave me success.
Thank you!

**Review by crystalz2022 — APPROVED** [review]
Approved and dry run test passed @anudishCGI @NataliaNikishina

**Pull request merged**
