### PR TITLE
Total Cost Override false Pharmacare Case Grid

### PR DESCRIPTION
**Pull request by anudishCGI**
Updated Total Cost Override field to non editable on case level grid Pharmacare base on the asks.

### CODE REVIEW

**Comment by anudishCGI** [comment]
https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-15068
Referencing this ticket for the current changes

**Review by rahul-mantri — APPROVED** [review]
Approved @anudishCGI

**Comment by anudishCGI** [comment]
Updated LWC Grids based on latest changes.
Grid Update:
Ambulance - made Source System ID editable for Manual Records.
Hospitalization - made total cost override read only for All Records, Source System ID editable for Manual Records
MSP - made total cost override read only for All Records, Source System ID editable for Manual Records
Pharmacare - made only All Records option available. Removed Manual Records from selection as business requirements change. Source System ID editable for Manual Records.
Thank You!
CC: @rahulmantriSFDC  @crystalz2022  @ahshaik1

**Review by rahul-mantri — APPROVED** [review]
Approved @anudishCGI

**Review by crystalz2022 — APPROVED** [review]
approved @anudishCGI

**Pull request merged**
